- name: Clone .dotfiles
  tags:
    - install
    - dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:bradleygore/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes # will loop through submodules
    update: yes
    accept_hostkey: yes
    version: main

- name: Stow .dotfiles
  tags:
    - install
    - dotfiles
  shell: cd $HOME/.dotfiles && ./install.zsh